services:
  frontend:
    build: ./frontend
    ports:
      - "80:80"
    depends_on:
      - backend
    networks:
      - dream_net

  backend:
    build: ./backend
    ports:
      - "3001:3001"
    env_file:
      - ./backend/.env
    depends_on:
      - db
    networks:
      - dream_net

  db:
    image: postgres:15
    restart: always
    environment:
      POSTGRES_USER: dreamuser
      POSTGRES_PASSWORD: dreampassword
      POSTGRES_DB: dreamvacations
    volumes:
      - dream_db_data:/var/lib/postgresql/data
    networks:
      - dream_net

volumes:
  dream_db_data:

networks:
  dream_net:
    driver: bridge
