version: '3.8'

services:
  frontend:
    image: ejehi/dreamvacation-frontend
    ports:
      - "3000:80"
    depends_on:
      - backend
    networks:
      - dreamnet

  backend:
    image: ejehi/dreamvacation-backend
    ports:
      - "5001:5000"
    env_file:
      - .env
    depends_on:
      - db
    networks:
      - dreamnet

  db:
    image: postgres:15-alpine
    restart: always
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
    volumes:
      - db_data:/var/lib/postgresql/data
    ports:
      - "5433:5432"
    networks:
      - dreamnet

networks:
  dreamnet:
    driver: bridge

volumes:
  db_data:
